name: Dokusho
description: A flutter application for reading manga

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web: any
  flutter_web_ui: any
  dio: ^2.1.0
  html_unescape: ^1.0.1+2
  photo_view: ^0.3.3
  flutter_speed_dial: ^1.1.2
  url_launcher: ^5.0.2
  providerscope: ^1.0.2
  path_provider: ^1.1.0

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  flutter_launcher_icons: ^0.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  image: 2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/blank.png
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf

flutter_icons:
  image_path: assets/launcher/icon.png
  android: true
  ios: true